name: Production Deployment

# Trigger the workflow when a release is created (with a version tag)
on:
  release:
    types: [published]  # When a release is published

jobs:
  request_approval:
    runs-on: ubuntu-latest
    environment:
      name: Production
      url: https://your-prod-env-url.com  # Optional: Add your production URL for reference
    permissions:
      contents: read  # Only need read permissions for the repository here
    steps:
      - name: Await manual approval for production deployment
        run: echo "Waiting for manual approval to deploy to production..."

  deploy_production:
    runs-on: ubuntu-latest
    needs: request_approval  # Deployment happens after approval
    environment: production
    if: github.event.review.state == 'approved'  # Only run if approved
    permissions:
      contents: write  # Need write permissions to deploy
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js (example)
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Run production build
        run: npm run build

      - name: Deploy to Production
        run: echo "Deploying version ${{ github.event.release.tag_name }} to production..."  # Replace with actual deployment command

      - name: Notify Success
        run: echo "Production deployment for version ${{ github.event.release.tag_name }} was successful!"